services:
    web:
        build: .
        volumes:
            - ./web:/app
            - ./package.json:/app/package.json
            - node_modules:/app/node_modules
        restart: ${RESTART_POLICY}
        env_file:
            - .env
        command: npm start
        # command: tail -f /dev/null #idle container
    api:
        build: .
        volumes:
            - ./api:/app
            - ./package.json:/app/package.json
            - node_modules:/app/node_modules
        restart: ${RESTART_POLICY}
        env_file:
            - .env
        command: npm start
    nginx:
        image: valian/docker-nginx-auto-ssl
        restart: ${RESTART_POLICY}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        environment:
            - SITES=${URL}=web:3000;api.${URL}=api:3000
            - FORCE_HTTPS=true
volumes:
    node_modules: