services:
    web:
        build: .
        volumes:
            - ./web:/app
            - node_modules:/app/node_modules
        restart: ${RESTART_POLICY}
        env_file:
            - .env
        command: npm start
        # command: tail -f /dev/null #idle container
        ports:
            - "80:3000"
volumes:
    node_modules: