version: '3'
services:
    php:
        image: php:8.2.11-cli-alpine3.18
        volumes:
            - ./runs:/app
        working_dir: /app
        # docker-compose run --rm php php hello.php
    node:
        image: node:16-alpine3.18
        volumes:
            - ./runs:/app
        working_dir: /app
        # docker-compose run --rm node node hello.js
    gcc:
        image: gcc:9.5.0
        volumes:
            - ./runs:/app
        working_dir: /app
        # docker-compose run --rm c /bin/bash -c "gcc hello.c -o hello && ./hello && rm hello"
    python:
        image: python:3.11.6-alpine3.18
        volumes:
            - ./runs:/app
        working_dir: /app
        # docker-compose run --rm python python hello.py
